{pkgs}: {
  deps = [
    pkgs.util-linux
    pkgs.wayland
    pkgs.libxkbcommon
    pkgs.xorg.libXdmcp
    pkgs.xorg.libXau
    pkgs.xorg.libxcb
    pkgs.libgbm
    pkgs.alsa-lib
    pkgs.cairo
    pkgs.pango
    pkgs.gtk3
    pkgs.mesa
    pkgs.xorg.libXrandr
    pkgs.xorg.libXfixes
    pkgs.xorg.libXext
    pkgs.xorg.libXdamage
    pkgs.xorg.libXcomposite
    pkgs.xorg.libX11
    pkgs.libdrm
    pkgs.expat
    pkgs.dbus
    pkgs.cups
    pkgs.atk
    pkgs.nspr
    pkgs.nss
    pkgs.glib
    pkgs.cpio
    pkgs.bomutils
    pkgs.xar
  ];
}
