import { beforeEach, describe, expect, it, vi } from "vitest";

const mockDbQuery = vi.fn();

vi.mock("../lib/db", () => ({
  db: {
    query: (...args: unknown[]) => mockDbQuery(...args),
  },
}));

vi.mock("../lib/logger", () => ({
  logger: { info: vi.fn(), warn: vi.fn(), error: vi.fn() },
}));

import {
  reconcileLegacyAutoGeneratedTitles,
  runBackfill,
} from "./addressBookBackfill";

beforeEach(() => {
  vi.clearAllMocks();
});

describe("reconcileLegacyAutoGeneratedTitles", () => {
  it("compacts only auto-created titles and records the reconciliation once", async () => {
    mockDbQuery.mockImplementation((sql: string) => {
      if (/SELECT p\.id, p\.canonical_name/i.test(sql)) {
        return Promise.resolve({
          rows: [{
            id: "place-auto",
            canonical_name: "Cedar Heights, Floor 4, Apt 12B",
            area: null,
            delivery_address: { address: "Cedar Heights, Floor 4, Apt 12B" },
          }],
        });
      }
      if (/UPDATE places\s+SET canonical_name/i.test(sql)) {
        return Promise.resolve({ rows: [{ id: "place-auto" }], rowCount: 1 });
      }
      return Promise.resolve({ rows: [] });
    });

    await reconcileLegacyAutoGeneratedTitles("ws-1");

    const update = mockDbQuery.mock.calls.find((call) =>
      /UPDATE places\s+SET canonical_name/i.test(String(call[0])),
    );
    expect(update?.[1]).toEqual([
      "Cedar Heights",
      "place-auto",
      "ws-1",
      "Cedar Heights, Floor 4, Apt 12B",
    ]);
    expect(mockDbQuery.mock.calls.some((call) =>
      /VALUES \(\$1, \$2, 'historical_reconciliation'/i.test(String(call[0])) &&
      call[1]?.[1] === "title_compacted",
    )).toBe(true);
    expect(String(mockDbQuery.mock.calls[0]?.[0])).toContain("canonical_name_source = 'auto'");
  });

  it("is idempotent when a prior reconciliation already stored the compact title", async () => {
    mockDbQuery.mockImplementation((sql: string) => {
      if (/SELECT p\.id, p\.canonical_name/i.test(sql)) {
        return Promise.resolve({
          rows: [{
            id: "place-auto",
            canonical_name: "Cedar Heights",
            area: null,
            delivery_address: { address: "Cedar Heights, Floor 4" },
          }],
        });
      }
      return Promise.resolve({ rows: [] });
    });

    await reconcileLegacyAutoGeneratedTitles("ws-1");

    expect(mockDbQuery.mock.calls.some((call) =>
      /UPDATE places\s+SET canonical_name/i.test(String(call[0])),
    )).toBe(false);
  });

  it("recognizes AUH from legacy title and aliases, then promotes only the automatic Residence", async () => {
    mockDbQuery.mockImplementation((sql: string) => {
      if (/SELECT p\.id, p\.canonical_name/i.test(sql)) {
        return Promise.resolve({
          rows: [{
            id: "place-auh",
            canonical_name: "AUH, Floor 4, Room 412",
            place_type: "residence",
            area: null,
            aliases: ["American University Hospital"],
            delivery_address: { address: "AUH, Floor 4, Room 412" },
          }],
        });
      }
      if (/UPDATE places\s+SET canonical_name/i.test(sql)) {
        return Promise.resolve({ rows: [{ id: "place-auh" }] });
      }
      if (/UPDATE places\s+SET place_type = 'hospital'/i.test(sql)) {
        return Promise.resolve({ rows: [{ id: "place-auh" }] });
      }
      return Promise.resolve({ rows: [] });
    });

    await reconcileLegacyAutoGeneratedTitles("ws-1");

    const titleUpdate = mockDbQuery.mock.calls.find((call) =>
      /UPDATE places\s+SET canonical_name/i.test(String(call[0])),
    );
    expect(titleUpdate?.[1]).toEqual([
      "AUH Hospital",
      "place-auh",
      "ws-1",
      "AUH, Floor 4, Room 412",
    ]);
    expect(
      mockDbQuery.mock.calls.some((call) =>
        /UPDATE places\s+SET place_type = 'hospital'[\s\S]*canonical_name_source = 'auto'/i.test(String(call[0])),
      ),
    ).toBe(true);
    expect(
      mockDbQuery.mock.calls.some((call) =>
        /'place_type_corrected', 'historical_reconciliation'/i.test(String(call[0])),
      ),
    ).toBe(true);
  });

  it("groups historical AUH variants under the hospital identity before creating a place", async () => {
    mockDbQuery.mockImplementation((sql: string) => {
      if (/FROM order_place_links opl\s+JOIN orders o/i.test(sql)) return Promise.resolve({ rows: [] });
      if (/FROM orders o/i.test(sql)) {
        return Promise.resolve({
          rows: [{
            id: "order-auh",
            workspace_owner_id: "ws-1",
            display_order_number: "1001",
            ordered_at: null,
            delivery_address: {
              address: "Ward C, Room 412",
              placeName: "A.U.H. Hospital",
              city: "Beirut",
            },
            contact_phone: null,
            delivery_contact_ids: [],
          }],
        });
      }
      if (/SELECT p\.id, p\.canonical_name/i.test(sql)) return Promise.resolve({ rows: [] });
      if (/SELECT pa\.id, pa\.place_id/i.test(sql)) return Promise.resolve({ rows: [] });
      if (/SELECT id, canonical_name, city_id FROM places/i.test(sql)) return Promise.resolve({ rows: [] });
      if (/SELECT id, place_type FROM places/i.test(sql)) return Promise.resolve({ rows: [] });
      if (/JOIN place_aliases pa/i.test(sql)) return Promise.resolve({ rows: [] });
      if (/INSERT INTO places/i.test(sql)) return Promise.resolve({ rows: [{ id: "place-auh" }] });
      return Promise.resolve({ rows: [], rowCount: 1 });
    });

    const summary = await runBackfill({ workspaceId: "ws-1" });

    expect(summary).toMatchObject({ places_created: 1, order_links_created: 1 });
    const insert = mockDbQuery.mock.calls.find((call) => /INSERT INTO places/i.test(String(call[0])));
    expect(insert?.[1]).toEqual(["ws-1", "AUH Hospital", "hospital", null]);
  });

  it("uses a named-hospital place field when historical address text is room-only", async () => {
    mockDbQuery.mockImplementation((sql: string) => {
      if (/FROM order_place_links opl\s+JOIN orders o/i.test(sql)) return Promise.resolve({ rows: [] });
      if (/FROM orders o/i.test(sql)) {
        return Promise.resolve({
          rows: [{
            id: "order-st-george",
            workspace_owner_id: "ws-1",
            display_order_number: "1002",
            ordered_at: null,
            delivery_address: {
              address: "Ward C, Room 412",
              placeName: "St George Hospital",
              city: "Beirut",
            },
            contact_phone: null,
            delivery_contact_ids: [],
          }],
        });
      }
      if (/SELECT p\.id, p\.canonical_name/i.test(sql)) return Promise.resolve({ rows: [] });
      if (/SELECT pa\.id, pa\.place_id/i.test(sql)) return Promise.resolve({ rows: [] });
      if (/SELECT id, canonical_name, city_id FROM places/i.test(sql)) return Promise.resolve({ rows: [] });
      if (/SELECT id, place_type FROM places/i.test(sql)) return Promise.resolve({ rows: [] });
      if (/JOIN place_aliases pa/i.test(sql)) return Promise.resolve({ rows: [] });
      if (/INSERT INTO places/i.test(sql)) return Promise.resolve({ rows: [{ id: "place-st-george" }] });
      return Promise.resolve({ rows: [], rowCount: 1 });
    });

    await runBackfill({ workspaceId: "ws-1" });

    const insert = mockDbQuery.mock.calls.find((call) => /INSERT INTO places/i.test(String(call[0])));
    expect(insert?.[1]).toEqual(["ws-1", "St George Hospital", "hospital", null]);
  });

  it("extracts a generic hospital title from historical delivery prose", async () => {
    mockDbQuery.mockImplementation((sql: string) => {
      if (/FROM order_place_links opl\s+JOIN orders o/i.test(sql)) return Promise.resolve({ rows: [] });
      if (/FROM orders o/i.test(sql)) {
        return Promise.resolve({
          rows: [{
            id: "order-city-hospital",
            workspace_owner_id: "ws-1",
            display_order_number: "1003",
            ordered_at: null,
            delivery_address: { address: "Jane Doe at City Hospital, Ward C, Room 412", city: "Beirut" },
            contact_phone: null,
            delivery_contact_ids: [],
          }],
        });
      }
      if (/SELECT p\.id, p\.canonical_name/i.test(sql)) return Promise.resolve({ rows: [] });
      if (/SELECT pa\.id, pa\.place_id/i.test(sql)) return Promise.resolve({ rows: [] });
      if (/SELECT id, canonical_name, city_id FROM places/i.test(sql)) return Promise.resolve({ rows: [] });
      if (/SELECT id, place_type FROM places/i.test(sql)) return Promise.resolve({ rows: [] });
      if (/JOIN place_aliases pa/i.test(sql)) return Promise.resolve({ rows: [] });
      if (/INSERT INTO places/i.test(sql)) return Promise.resolve({ rows: [{ id: "place-city-hospital" }] });
      return Promise.resolve({ rows: [], rowCount: 1 });
    });

    await runBackfill({ workspaceId: "ws-1" });

    const insert = mockDbQuery.mock.calls.find((call) => /INSERT INTO places/i.test(String(call[0])));
    expect(insert?.[1]).toEqual(["ws-1", "City Hospital", "hospital", null]);
  });

  it("repairs a legacy generic hospital title without retaining delivery prose", async () => {
    mockDbQuery.mockImplementation((sql: string) => {
      if (/SELECT p\.id, p\.canonical_name/i.test(sql)) {
        return Promise.resolve({
          rows: [{
            id: "place-city-hospital",
            canonical_name: "Jane Doe at City Hospital",
            place_type: "residence",
            area: null,
            aliases: [],
            delivery_address: { address: "Jane Doe at City Hospital, Ward C" },
          }],
        });
      }
      if (/UPDATE places\s+SET canonical_name/i.test(sql)) {
        return Promise.resolve({ rows: [{ id: "place-city-hospital" }] });
      }
      if (/UPDATE places\s+SET place_type = 'hospital'/i.test(sql)) {
        return Promise.resolve({ rows: [{ id: "place-city-hospital" }] });
      }
      return Promise.resolve({ rows: [] });
    });

    await reconcileLegacyAutoGeneratedTitles("ws-1");

    const titleUpdate = mockDbQuery.mock.calls.find((call) =>
      /UPDATE places\s+SET canonical_name/i.test(String(call[0])),
    );
    expect(titleUpdate?.[1]).toEqual([
      "City Hospital",
      "place-city-hospital",
      "ws-1",
      "Jane Doe at City Hospital",
    ]);
  });

  it("merges two similar hospital groups (≥ 0.75) within the same city into one place", async () => {
    // Two hospital addresses that differ only by a department suffix should produce one place.
    // "rassoul al azam hospital" vs "rassoul al azam hospital cardiology" — similarity > 0.75.
    mockDbQuery.mockImplementation((sql: string) => {
      if (/FROM order_place_links opl\s+JOIN orders o/i.test(sql)) return Promise.resolve({ rows: [] });
      if (/FROM orders o/i.test(sql)) {
        return Promise.resolve({
          rows: [
            {
              id: "order-rassoul-1",
              workspace_owner_id: "ws-1",
              display_order_number: "1010",
              ordered_at: null,
              delivery_address: { address: "Rassoul Al Azam Hospital, Room 3", city: "Beirut" },
              contact_phone: null,
              delivery_contact_ids: [],
            },
            {
              id: "order-rassoul-2",
              workspace_owner_id: "ws-1",
              display_order_number: "1011",
              ordered_at: null,
              delivery_address: { address: "Rassoul Al Azam Hospital Cardiology Dept", city: "Beirut" },
              contact_phone: null,
              delivery_contact_ids: [],
            },
          ],
        });
      }
      if (/SELECT p\.id, p\.canonical_name/i.test(sql)) return Promise.resolve({ rows: [] });
      if (/SELECT pa\.id, pa\.place_id/i.test(sql)) return Promise.resolve({ rows: [] });
      if (/SELECT id, canonical_name, city_id FROM places/i.test(sql)) return Promise.resolve({ rows: [] });
      if (/SELECT id, place_type FROM places/i.test(sql)) return Promise.resolve({ rows: [] });
      if (/JOIN place_aliases pa/i.test(sql)) return Promise.resolve({ rows: [] });
      if (/INSERT INTO places/i.test(sql)) return Promise.resolve({ rows: [{ id: "place-rassoul" }] });
      return Promise.resolve({ rows: [], rowCount: 1 });
    });

    const summary = await runBackfill({ workspaceId: "ws-1" });

    // Both orders should collapse into one place, not two
    expect(summary.places_created).toBe(1);
    expect(summary.order_links_created).toBe(2);
    const inserts = mockDbQuery.mock.calls.filter((call) => /INSERT INTO places/i.test(String(call[0])));
    expect(inserts).toHaveLength(1);
    // Survivor keeps the shorter canonical text
    expect(inserts[0]?.[1]?.[1]).toBe("Rassoul Al Azam Hospital");
  });

  it("keeps only exact AUH institutional aliases and retires mixed patient delivery text", async () => {
    mockDbQuery.mockImplementation((sql: string) => {
      if (/SELECT p\.id, p\.canonical_name/i.test(sql)) return Promise.resolve({ rows: [] });
      if (/SELECT pa\.id, pa\.place_id/i.test(sql)) {
        return Promise.resolve({
          rows: [{
            id: "alias-private",
            place_id: "place-auh",
            canonical_name: "AUH Hospital",
            alias_text: "AUH Hospital, patient Jane Doe",
            source: "legacy_untrusted",
            approval_state: "unapproved",
          }],
        });
      }
      return Promise.resolve({ rows: [] });
    });

    await reconcileLegacyAutoGeneratedTitles("ws-1");

    const retiredAlias = mockDbQuery.mock.calls.find((call) =>
      /UPDATE place_aliases\s+SET deleted_at = now\(\)/i.test(String(call[0])),
    );
    expect(retiredAlias?.[1]).toEqual(["alias-private"]);
  });
});