const colors = {
  light: {
    text: "#0f1624",
    tint: "#0a3f4d",
    background: "#f9fafb",
    foreground: "#0f1624",
    card: "#ffffff",
    cardForeground: "#0f1624",
    primary: "#0a3f4d",
    primaryForeground: "#ffffff",
    secondary: "#eff1f5",
    secondaryForeground: "#374766",
    muted: "#eff1f5",
    mutedForeground: "#525f7a",
    accent: "#eff1f5",
    accentForeground: "#374766",
    destructive: "#ef4343",
    destructiveForeground: "#ffffff",
    border: "#e1e4eb",
    input: "#e1e4eb",
    success: "#16a34a",
    successForeground: "#ffffff",
    warning: "#d97706",
    warningForeground: "#ffffff",
  },
  dark: {
    text: "#f0f4fb",
    tint: "#4cc9e0",
    background: "#0c0f1a",
    foreground: "#f0f4fb",
    card: "#141828",
    cardForeground: "#f0f4fb",
    primary: "#4cc9e0",
    primaryForeground: "#0a3f4d",
    secondary: "#1e2436",
    secondaryForeground: "#c5cfe0",
    muted: "#1e2436",
    mutedForeground: "#7a8ba5",
    accent: "#1e2436",
    accentForeground: "#c5cfe0",
    destructive: "#ef4343",
    destructiveForeground: "#ffffff",
    border: "#2a3048",
    input: "#2a3048",
    success: "#22c55e",
    successForeground: "#ffffff",
    warning: "#f59e0b",
    warningForeground: "#ffffff",
  },
  radius: 6,
};

export default colors;
